# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '00:27'
      timezone: 'Etc/UTC'
    labels:
      - dependencies
      - ginger
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
      time: '01:27'
      timezone: 'Etc/UTC'
    labels:
      - dependencies
      - java
      - ginger
    registries:
      - coremedia-cms-releases
registries:
  coremedia-cms-releases:
    type: maven-repository
    url: https://repository.coremedia.com/nexus/content/groups/cms
    username: ${{ secrets.NEXUS_GITHUB_ACTIONS_READONLY_USERNAME }}
    password: ${{ secrets.NEXUS_GITHUB_ACTIONS_READONLY_TOKEN }}
