# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: weekly
    reviewers:
      - 'CoreMedia/toko'
    registries:
      - maven-github
registries:
  maven-github:
    type: maven-repository
    url: https://repository.coremedia.com/nexus/content/groups/cms
    username: ${{ secrets.PLUGINS_NEXUS_USER }}
    password: ${{ secrets.PLUGINS_NEXUS_PASSWORD }}
