format: sarif
output: trivy-results.sarif

severity:
  - MEDIUM
  - HIGH
  - CRITICAL

scan:
  skip-files:
    - /coremedia/prometheus/jmx_prometheus_javaagent.jar
    - /usr/bin/confd

pkg-types:
  - library
