# This is the workflow pipeline that runs the default build and checks that are
# needed for this repository. It is triggered by commits on the base branches
# and in pull requests to execute the differential checks that are required the
# pull request. Furthermore, it is triggered regularly to notify about recent
# security issues or other external changes that may break the project checks.

name: Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Cache Maven Repo'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 'Set up Maven settings'
        uses: s4u/maven-settings-action@v2.7.0
        with:
          servers: |
            [{
              "id": "coremedia.external.releases",
              "username": "${{ secrets.PLUGINS_NEXUS_USER }}",
              "password": "${{ secrets.PLUGINS_NEXUS_PASSWORD }}"
            },
            {
              "id": "coremedia.internal.releases",
              "username": "${{ secrets.PLUGINS_NEXUS_USER }}",
              "password": "${{ secrets.PLUGINS_NEXUS_PASSWORD }}"
            }]
            
      - name: 'Build with Maven'
        run: mvn --batch-mode --update-snapshots verify
  
