# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Trivy

on:
  workflow_call:
    inputs:
      fail_on_issues:
        type: boolean
        default: false
    outputs:
      teams_fact:
        value: |
          {
            "name": "Trivy Image Scan:",
            "value": "${{ jobs.trivy.outputs.result }}"
          }

jobs:
  trivy:
    name: Image Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    outputs:
      result: ${{ job.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: coremedia.external.releases
          server-username: PLUGINS_NEXUS_USER
          server-password: PLUGINS_NEXUS_PASSWORD
          cache: maven

      - name: Build Docker image with Maven
        run: |
          mvn --batch-mode \
              install \
              -Pdefault-image \
              -Dapplication.image-tag=${{ github.sha }} \
              -Denforcer.skip=true \
              -Dmdep.analyze.skip=true \
              -DskipTests=true \
              -Dsort.skip=true
        env:
          PLUGINS_NEXUS_USER: ${{ secrets.PLUGINS_NEXUS_USER }}
          PLUGINS_NEXUS_PASSWORD: ${{ secrets.PLUGINS_NEXUS_PASSWORD }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.9.1
        with:
          image-ref: 'coremedia/headless-server-commerce:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          trivyignores: '.trivyignore'
          exit-code: ${{ inputs.fail_on_issues && '1' || '0' }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
